# Generated by Django 4.0.4 on 2022-06-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_prod',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=1, verbose_name='precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id producto'),
        ),
        migrations.DeleteModel(
            name='venta_producto',
        ),
    ]
